# Site settings
title: Ihsan Gunawans
subtitle: "Official Blog Of Ihsan Gunawans"
header-img: img/bgberanda.jpg
image: img/ihsangunawans-home.jpg
copyright_name: Ihsan Gunawans
description: "Hanya Seorang Petani Yang Berusaha untuk Selalu Menanam Kebaikan."
url: "https://ihsangunawans.github.io"
author: Ihsan Gunawans
twitter_username: ihsangunawans
github_username: ihsangunawans
facebook_username: ihsangunawans
email_username:  xxxxxxxxx@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
