title:              Ihsan Gunawans
email:              your-email@example.com
description:        Personal Blog Of Ihsan Gunawans
author:             Ihsan Gunawans
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://ihsangunawans.github.io"

# Social Profiles
twitter_username:   ihsangunawans
github_username:    ihsangunawans
facebook_username:  ihsangunawans
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
